# This is the deployment for cPanel based deployment with GitHub integration in cPanel.
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/varterjr/public_html/
    - /bin/cp -R _site $DEPLOYPATH
